name: First-workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: echo "Hello, World!"
            - name: Multi line command
              run: |
                node -v
                npm -v

    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW version
              run: sw_vers
    depedant-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: Echo a string
              run: Write-Output "This is a dependent job and writes string as Windows String"
            - name: Error Step
              run: doesnotexistss